## IMPORT LIBRARIES AND DATA

In [5]:
import numpy as np
import pandas as pd

In [6]:
!pwd > path.txt
file_ptr = open('path.txt','r')
path = file_ptr.read()
path = path[:-1]

In [7]:
df = pd.read_csv(str(path) +'/data.csv',encoding= 'unicode_escape')
df

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[541909 rows x 8 columns]

## DATA PROCESSING

In [8]:
df = df[["CustomerID","Description","Quantity","UnitPrice","Country"]]
df.dropna()
df

CustomerID                          Description  Quantity  UnitPrice  \
0          17850.0   WHITE HANGING HEART T-LIGHT HOLDER         6       2.55   
1          17850.0                  WHITE METAL LANTERN         6       3.39   
2          17850.0       CREAM CUPID HEARTS COAT HANGER         8       2.75   
3          17850.0  KNITTED UNION FLAG HOT WATER BOTTLE         6       3.39   
4          17850.0       RED WOOLLY HOTTIE WHITE HEART.         6       3.39   
...            ...                                  ...       ...        ...   
541904     12680.0          PACK OF 20 SPACEBOY NAPKINS        12       0.85   
541905     12680.0         CHILDREN'S APRON DOLLY GIRL          6       2.10   
541906     12680.0        CHILDRENS CUTLERY DOLLY GIRL          4       4.15   
541907     12680.0      CHILDRENS CUTLERY CIRCUS PARADE         4       4.15   
541908     12680.0        BAKING SET 9 PIECE RETROSPOT          3       4.95   

               Country  
0       United Kingdom  
1       United Kingdom  
2       United Kingdom  
3       United Kingdom  
4       United Kingdom  
...                ...  
541904          France  
541905          France  
541906          France  
541907          France  
541908          France  

[541909 rows x 5 columns]

In [9]:
description_dictionary = {}
country_dictionary = {}
data = df.to_numpy()
num_of_rows = data.shape[0]
description_count = 1
country_count = 1

for i in range(num_of_rows):
    description = data[i][1]
    country = data[i][4]
    
    if description not in description_dictionary:
        description_dictionary[description] = description_count
        description_count = description_count + 1
    
    if country not in country_dictionary:
        country_dictionary[country] = country_count
        country_count = country_count + 1
    
print(len(country_dictionary))
print(len(description_dictionary))

38
4224


In [10]:
for i in range(num_of_rows):
    data[i][1] = description_dictionary[data[i][1]]
    data[i][4] = country_dictionary[data[i][4]]

print(data)

[[17850.0 1 6 2.55 1]
 [17850.0 2 6 3.39 1]
 [17850.0 3 8 2.75 1]
 ...
 [12680.0 3213 4 4.15 2]
 [12680.0 3219 4 4.15 2]
 [12680.0 2349 3 4.95 2]]


In [11]:
df = pd.DataFrame(data, columns=["CustomerID","ItemID","Quantity","UnitPrice","CountryID"])
df

CustomerID ItemID Quantity UnitPrice CountryID
0         17850.0      1        6      2.55         1
1         17850.0      2        6      3.39         1
2         17850.0      3        8      2.75         1
3         17850.0      4        6      3.39         1
4         17850.0      5        6      3.39         1
...           ...    ...      ...       ...       ...
541904    12680.0   2019       12      0.85         2
541905    12680.0    418        6       2.1         2
541906    12680.0   3213        4      4.15         2
541907    12680.0   3219        4      4.15         2
541908    12680.0   2349        3      4.95         2

[541909 rows x 5 columns]

In [34]:
df.to_csv("processed_data.csv")